from environmental_objects import *
from items import *
from npc import *


stuff = dict([
    ('aleph', AlephNaught()),
    ('antinomy', Antinomy()),
    ('ats', Ats()),
    ('gummy bears', Bears()),
    ('armored branch', Branch()),
    ('armored manuport', Manuport2()),
    ('axiom of choice', Choice()),
    ('blue', StygianBlue()),
    ('bottle', Bottle()),
    ('calculus', Calculus()),
    ('campari', Campari()),
    ('cappuccino', Cappuccino()),
    ('car', Car()),
    ('chainsaw', Chainsaw()),
    ('chair armor', ChairArmor()),
    ('chicken', Chick()),
    ('chuck', ChuckThePlant()),
    ('cluster point', ClusterPoint()),
    ('comic sans', ComicSans()),
    ('completeness theorem', Godel()),
    ('continuum hypothesis', Continuum()),
    ('cookies', HomemadeCookies()),
    ('croissant', CremeCroissant()),
    ('cutlass', CutlassOfKaflu()),
    ('deliverance', Deliverance()),
    ('discourse', Method()),
    ('falsidical paradox', Falsidical()),
    ('ginseng', Ginseng()),
    ('gommo', Gommo()),
    ('great attractor', GreatAttractor()),
    ('iron armor', IronArmor()),
    ('lift', Album()),
    ('logistic map', LogisticMap()),
    ('major fern potion', MajorFernPotion()),
    ('manuport', Manuport()),
    ('minor fern potion', MinorFernPotion()),
    ('modification', Modification()),
    ('m-theory', MTheory()),
    ('mushroom armor', FungineArmor()),
    ('n-dimensional polytope', Polytope()),
    ('nimby', Nimby()),
    ('non standard analysis', Analysis()),
    ('orange', HyperbolicOrange()),
    ('panna cotta', PannaCotta()),
    ('polarized sheet', Sheet()),
    ('portal device', HandheldPortalDevice()),
    ('red', SelfLuminousRed()),
    ('riemann', Riemann()),
    ('sep', Sep()),
    ('sharp polyhedron', Polyhedron()),
    ('specimen', Specimen()),
    ('strudel', Strudel()),
    ('suspicious mushrooms', SusMushrooms()),
    ('tesseract', Tesseract()),
    ('transparent polygon', Polygon()),
    ('veridical paradox', Veridical()),
    ('wireless wire', Wire()),
    ('rina armor', RinaArmor()),
    ('tesla', TeslaArmor()),
    ('ultimate insult', UltimateInsult())
])

weapons_dict= dict([
    ('armored branch', Branch()),
    ('armored manuport', Manuport2()),
    ('chainsaw', Chainsaw()),
    ('chicken', Chick()),
    ('cutlass', CutlassOfKaflu()),
    ('deliverance', Deliverance()),
    ('great attractor', GreatAttractor()),
    ('manuport', Manuport()),
    ('n-dimensional polytope', Polytope()),
    ('polarized sheet', Sheet()),
    ('portal device', HandheldPortalDevice()),
    ('sharp polyhedron', Polyhedron()),
    ('tesseract', Tesseract()),
    ('transparent polygon', Polygon()),
    ('wireless wire', Wire())
])

curses_dict = dict([
    ('aleph', AlephNaught()),
    ('antinomy', Antinomy()),
    ('axiom of choice', Choice()),
    ('blue', StygianBlue()),
    ('calculus', Calculus()),
    ('cluster point', ClusterPoint()),
    ('comic sans', ComicSans()),
    ('completeness theorem', Godel()),
    ('continuum hypothesis', Continuum()),
    ('discourse', Method()),
    ('falsidical paradox', Falsidical()),
    ('logistic map', LogisticMap()),
    ('nimby', Nimby()),
    ('non standard analysis', Analysis()),
    ('orange', HyperbolicOrange()),
    ('riemann', Riemann()),
    ('red', SelfLuminousRed()),
    ('sep', Sep()),
    ('veridical paradox', Veridical()),
    ('ultimate insult', UltimateInsult())
])

consumables_dict = dict([
    ('ats', Ats()),
    ('cappuccino', Cappuccino()),
    ('gummy bears', Bears()),
    ('cookies', HomemadeCookies()),
    ('croissant', CremeCroissant()),
    ('gommo', Gommo()),
    ('modification', Modification()),
    ('panna cotta', PannaCotta()),
    ('suspicious mushrooms', SusMushrooms()),
    ('strudel', Strudel())
])

mrs_dict = dict([
    ('lift', Album()),
    ('campari', Campari()),
    ('ginseng', Ginseng()),
    ('grog', Grog()),
    ('major fern potion', MajorFernPotion()),
    ('minor fern potion', MinorFernPotion())
])

weapons_list =  [Branch(),   
                Manuport2(),
                Chainsaw(),
                Chick(),
                CutlassOfKaflu(),
                Deliverance(),
                GreatAttractor(),
                Manuport(),
                Polytope(),
                Sheet(),
                HandheldPortalDevice(),
                Polyhedron(),
                Tesseract(),
                Polygon(),
                Wire()]

curses_list = [AlephNaught(),
               Antinomy(),
               Choice(),
               StygianBlue(),
               Calculus(),
               ClusterPoint(),
               ComicSans(),
               Godel(),
               Continuum(),
               Method(),
               Falsidical(),
               LogisticMap(),
               Nimby(),
               Analysis(),
               HyperbolicOrange(),
               Riemann(),
               SelfLuminousRed(),
               Sep(),
               Veridical(),
               UltimateInsult()]

consumables_list = [Ats(),
                    Bears(),
                    HomemadeCookies(),
                    CremeCroissant(),
                    Gommo(),
                    Modification(),
                    PannaCotta(),
                    SusMushrooms(),
                    Strudel()]

mrs_list = [Album(),
            Campari(),
            Ginseng(),
            Grog(),
            MajorFernPotion(),
            MinorFernPotion()]

armors_list = [Album(),
               ChairArmor(),
               FungineArmor(),
               RinaArmor(),
               MultidimensionalArmor(),
               TeslaArmor()]


all_objects = weapons_list + curses_list + consumables_list + mrs_list + armors_list
weapons_armors = weapons_list + armors_list